"""Rebuild bundled translations: uv run --with opencc-python-reimplemented tool/build_translations.py."""
import json
from pathlib import Path
from opencc import OpenCC

root = Path(__file__).resolve().parents[1]
converter = OpenCC('s2t')
rows = {}
for line in (root / 'tool/translations.tsv').read_text(encoding='utf-8').splitlines():
    if not line:
        continue
    source, en, ja, ko = [s.replace(r'\n', '\n') for s in line.split('|')]
    assert source not in rows, source
    rows[source] = [converter.convert(source), en, ja, ko]

def dart(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')

out = '// Generated by tool/build_translations.py. Edit tool/translations.tsv.\n'
out += '// Columns: Traditional Chinese, English, Japanese, Korean.\n'
out += 'const translations = <String, List<String>>{\n'
for key, values in rows.items():
    out += f'  {dart(key)}: [{", ".join(map(dart, values))}],\n'
out += '};\n'
(root / 'lib/l10n').mkdir(exist_ok=True)
(root / 'lib/l10n/translations.dart').write_text(out, encoding='utf-8')
